Social_Network/Social_Network/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('dwitter.urls'), name='dwitter'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Network/accounts/urls.py
from django.urls import path
from .views import signup, activate

urlpatterns = [
    path('', signup, name='signup'),
    path('activate/<uid>/', activate, name='activate'),
]

Social_Network/dwitter/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile, ProfileUpdateView

app_name = "dwitter"

urlpatterns = [
    path("dashboard", dashboard, name='dashboard'),
    path("accounts/profile", profile_list, name='profile_list'),
    path("profile/<int:pk>", profile, name='profile'),
    path("edit/", ProfileUpdateView.as_view(), name='edit'),
]

Social_Network/accounts/models.py
from django.db import models
from django.conf import settings


class LoggedInUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='logged_in_user', on_delete=models.CASCADE)
    session_key = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return self.user.username

Social_Network/dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    image = models.ImageField(upload_to='images', blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user.username}"
            f"({self.data:%Y-%m-%d-%H:%M}):"
        )


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance,)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()


class Dweet(models.Model):
    user = models.ForeignKey(User,
                             related_name='dweets',
                             on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user}"
            f"({self.created_at:%Y-%m-%d-%H:%M}):"
            f"{self.body[:30]}..."
        )

Social_Network/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Social_Network/dwitter/forms.py
from django import forms
from .models import Dweet, Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user',  'image']

        widgets = {
            'image': forms.FileInput(attrs={'accept': 'images/*'}),
        }


class DweetFrom(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Dweet something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )

    class Meta:
        model = Dweet
        exclude = ("user", )

Social_Network/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from .forms import SignupForm
# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # save form in the memory not in database
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': str(user.pk),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})


def activate(request, uid):
    User = get_user_model()

    try:
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None:
        # The user is valid
        user.is_active = True
        user.save()
        return redirect('login')
    else:
        # The user is not valid
        return HttpResponse('Activation link is invalid!')

Social_Network/dwitter/views.py
from django.shortcuts import render, reverse
from django.views.generic import UpdateView
from .models import Profile, Dweet
from .forms import DweetFrom, UserForm
from django.shortcuts import redirect
# Create your views here.


def dashboard(request):
    form = DweetFrom(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("dwitter:dashboard")

    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("created_at")

    return render(
        request, 'dwitter/dashboard.html',
        {"form": form, "dweets":followed_dweets},
    )


def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, 'dwitter/profile_list.html', {'profiles': profiles})


def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)

    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, 'dwitter/profile.html', {'profile': profile})


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = UserForm
    template_name = 'edit.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_success_url(self):
        return reverse('dwitter:profile', kwargs={'pk': self.object.pk})

Social_Network/dwitter/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Dwitter</title>
</head>
<body>
  <a href="{% url 'dwitter:dashboard'%}">
  <section class="hero is-small is-success mb-4">
    <div class="hero-body">
        <h1 class="title is-1">Dwitter</h1>
        <p class="subtitle is-4">Your tiny social network built with Django</p>
    </div>
  </section>
  </a>
  <div class="container">
      <div class="columns">
        {% block content%}
        {% endblock%}
      </div>
  </div>
</body>
</html>

Social_Network/dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="column">
    {% for followed in user.profile.follows.all %}
        {% for dweet in followed.user.dweets.all %}
            <div class="box">
                {{dweet.body}}
                <span class="is-small has-text-grey-light">
                    ({{ dweet.created_at }} by {{ dweet.user.username }}
                </span>
            </div>
        {% endfor %}
    {% endfor %}
</div>

<div class="block">
    <div class="block">
    <a href="{% url 'dwitter:profile_list' %} ">
        <button class="button is-dark is-outlined is-fullwidth">
            All Profiles
        </button>
    </a>
</div>
<div class="block">
    <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
        <button class="button is-success is-light is-outlined is-fullwidth">
            My Profile
        </button>
    </a>
</div>
    <div class="block">
        <h2 class="title is-2">Add a Dweet</h2>
    </div>

    <div class="block">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-success is-fullwidth is-medium mt-5"
                    type="submit">Dweet
            </button>
        </form>
    </div>
</div>

{% endblock content%}

Social_Network/dwitter/templates/dwitter/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
        <h1 class="title is-1">
            {{profile.user.username|upper}}'s Dweets
        </h1>
        <span class="is-small has-text-grey-light">
                    ({{ profile.data }})
        </span>

    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">
                Follow
            </button>
            <button class="button is-danger"
                    name="follow"
                    value="unfollow">
                Unfollow
            </button>
        {% else %}
            <button class="button is-success"
                    name="follow"
                    value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">
                Unfollow
            </button>
        {% endif %}
        </div>
    </form>
    </div>

    <div class="content">
        {% for dweet in profile.user.dweets.all %}
            <div class="box">
                {{ dweet.body }}
                <span class="is-small has-text-grey-light">
                    ({{ dweet.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>

</div>

<div class="column is-one-third">
    <div class="block">
        <div style="margin-left:130px" >
                {% if profile.image %}
                <img src="{{profile.image.url}}" alt="" style="width:100px; height=150px; border-radius:50%;" >
                {% endif %}
        </div>
        <div class="block">
            <a href="{% url 'dwitter:edit' %}"><button class="button is-dark is-outlined is-fullwidth">Edit Profile</button></a>
        </div>
        <div class="block">
            <a href="{% url 'logout' %}"><button class="button is-dark is-outlined is-fullwidth">Log Out</button></a>
        </div>
    </div>

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
     <div class="block">
        <a href="{% url 'dwitter:dashboard' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                Home
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows: {{profile.follows.all.count}}
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitter:profile' following.id %} ">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by: {{profile.followed_by.all.count}}
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitter:profile' follower.id %} ">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

Social_Network/dwitter/templates/dwitter/profile_list.html
{% extends 'base.html'%}

{% block content%}

<div class="column">
   {% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'dwitter:profile' profile.id%}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}
</div>

{% endblock%}

Social_Network/dwitter/templates/edit.html
{% extends 'base.html'%}

{% load static %}
{% block content %}
  <h1>Edit Profile</h1>
  <form method="post" enctype="multipart/form-data" class="register-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}